//
//  Credentials.swift
//  PDFViewer
//
//  Created by Alexander Bustos on 12/30/16.
//  Copyright © 2016 Alexander Bustos. All rights reserved.
//

import Foundation

struct Crednetials {
    static let baseUrl = "http://lifebookbuilder.cloudapp.net:3000/api"
    static let token = "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1N2EyMDlmNGMyMDk3MWNjMGQxMTE1Y2IiLCJjcmVhdGVkIjoiMjAxNi0wOC0wM1QxNToxMjo1Mi45NDZaIiwicGFzc3dvcmQiOiIkMmEkMTAkOXczbjZtUkxMbFB5Z20wbk4zanljZUlrYWNjWEVsN2pJNC5WMmI2c2hPWVppdUVKeU9WUnEiLCJ1cGRhdGVkIjoiMjAxNi0xMi0yNlQxODozNjoxNS44MzhaIiwidXNlcm5hbWUiOiJhIiwidmVyc2lvbiI6MCwiY2hhcHRlcnMiOnsiQ2hhcHRlcl8xNiI6bnVsbCwiQ2hhcHRlcl8xNSI6bnVsbCwiQ2hhcHRlcl8xNCI6bnVsbCwiQ2hhcHRlcl8xMyI6bnVsbCwiQ2hhcHRlcl8xMiI6bnVsbCwiQ2hhcHRlcl8xMSI6bnVsbCwiQ2hhcHRlcl8xMCI6bnVsbCwiQ2hhcHRlcl8wOSI6bnVsbCwiQ2hhcHRlcl8wOCI6bnVsbCwiQ2hhcHRlcl8wNyI6bnVsbCwiQ2hhcHRlcl8wNiI6bnVsbCwiQ2hhcHRlcl8wNSI6bnVsbCwiQ2hhcHRlcl8wNCI6bnVsbCwiQ2hhcHRlcl8wMyI6bnVsbCwiQ2hhcHRlcl8wMiI6bnVsbCwiQ2hhcHRlcl8wMSI6IjU3YTIyZjhjYzIwOTcxY2MwZDExMTVlMyIsIkNoYXB0ZXJfMDAiOm51bGx9LCJpZCI6IjU3YTIwOWY0YzIwOTcxY2MwZDExMTVjYiJ9.v1qUGWeeNgJisW6bQ6LRNLUEMUqbwHMbycjKHTJ1h8A"
}
