//
//  Credentials.swift
//  PDFViewer
//
//  Created by Alexander Bustos on 12/30/16.
//  Copyright © 2016 Alexander Bustos. All rights reserved.
//

import Foundation

struct Crednetials {
    static let baseUrl = "http://lifebookbuilder.cloudapp.net:3000/api"
    static let token = "JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1Nzk4MDc2YmMyMDk3MWNjMGQxMTE1N2UiLCJjcmVhdGVkIjoiMjAxNi0wNy0yN1QwMDo1OToyMy43ODdaIiwicGFzc3dvcmQiOiIkMmEkMTAkS2tuLnpPbUJuVHFuSWZTbVJtRGhuLmxxTy9aN2ZBRE5KSXM2VnJsU0hmdFVXU0VKc1U1WnUiLCJ1cGRhdGVkIjoiMjAxNi0xMi0yNlQxODo0ODoyOS4zMjdaIiwidXNlcm5hbWUiOiJib3JrMTIzIiwidmVyc2lvbiI6MCwiY2hhcHRlcnMiOnsiQ2hhcHRlcl8xNiI6bnVsbCwiQ2hhcHRlcl8xNSI6bnVsbCwiQ2hhcHRlcl8xNCI6bnVsbCwiQ2hhcHRlcl8xMyI6bnVsbCwiQ2hhcHRlcl8xMiI6bnVsbCwiQ2hhcHRlcl8xMSI6bnVsbCwiQ2hhcHRlcl8xMCI6IjU3ZjQwYWRiYzIwOTcxY2MwZDExMTlkNyIsIkNoYXB0ZXJfMDkiOm51bGwsIkNoYXB0ZXJfMDgiOm51bGwsIkNoYXB0ZXJfMDciOm51bGwsIkNoYXB0ZXJfMDYiOiI1N2Y0MGFkYmMyMDk3MWNjMGQxMTE5ZDciLCJDaGFwdGVyXzA1IjpudWxsLCJDaGFwdGVyXzA0IjoiNTc5OGM0MjljMjA5NzFjYzBkMTExNTg3IiwiQ2hhcHRlcl8wMyI6IjU3OThjMmE2YzIwOTcxY2MwZDExMTU4MyIsIkNoYXB0ZXJfMDIiOiI1Nzk4YzI5YWMyMDk3MWNjMGQxMTE1ODIiLCJDaGFwdGVyXzAxIjoiNTc5OGMyNzJjMjA5NzFjYzBkMTExNTdmIn0sImlkIjoiNTc5ODA3NmJjMjA5NzFjYzBkMTExNTdlIn0.SADjZw9kUEZu19quB6zyuv4Vs-mCtR-9-XQtwuNwo_A"
}
